IMAGE_FORMAT = '%d.png'
PCD_FORMAT = '%d.npy'
LEFT_SHOULDER_RGB_FOLDER = 'left_shoulder_rgb'
LEFT_SHOULDER_DEPTH_FOLDER = 'left_shoulder_depth'
LEFT_SHOULDER_MASK_FOLDER = 'left_shoulder_mask'
RIGHT_SHOULDER_RGB_FOLDER = 'right_shoulder_rgb'
RIGHT_SHOULDER_DEPTH_FOLDER = 'right_shoulder_depth'
RIGHT_SHOULDER_MASK_FOLDER = 'right_shoulder_mask'
OVERHEAD_RGB_FOLDER = 'overhead_rgb'
OVERHEAD_DEPTH_FOLDER = 'overhead_depth'
OVERHEAD_MASK_FOLDER = 'overhead_mask'
WRIST_RGB_FOLDER = 'wrist_rgb'
WRIST_DEPTH_FOLDER = 'wrist_depth'
WRIST_MASK_FOLDER = 'wrist_mask'
FRONT_RGB_FOLDER = 'front_rgb'
FRONT_DEPTH_FOLDER = 'front_depth'
FRONT_MASK_FOLDER = 'front_mask'
FRONT_PCD_FOLDER = 'front_pcd'
EPISODES_FOLDER = 'episodes'
EPISODE_FOLDER = 'episode_%d'
VARIATIONS_FOLDER = 'variation%d'
JOINT_VELOCITIES_FOLDER = 'joint_velocities'
JOINT_POSITIONS_FOLDER = 'joint_positions'
GRIPPER_STATES_FOLDER = 'gripper_states'
LOW_DIM_PICKLE = 'low_dim_obs.pkl'
VARIATION_DESCRIPTIONS = 'variation_descriptions.pkl'

TTT_FILE = 'task_design.ttt'

DEPTH_SCALE = 2**24 - 1

